---
- hosts: all

  become: yes
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes 
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755

